services: 
  flask_server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx_conf/flask.conf:/etc/nginx/conf.d/default.conf:ro
    profiles: ["prod"]
  react_server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx_conf/flask.conf:/etc/nginx/conf.d/default.conf:ro
    profiles: ["prod"]    
  npm_production:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend/my-vue-app:/app
    ports:
      - "5173:5173"
    command: npm run build
    profiles: ["prod"]      
  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --debug
    profiles: ["dev"]
  db:
    image: mysql:8.4
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myrootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
    profiles: ["dev"]      
  npm:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend/my-vue-app:/app
    ports:
      - "5173:5173"
    command: npm run dev
    profiles: ["dev"]    
