services:
  flask:
    build: ./python/.
    ports:
      - 5000:5000
    volumes:
      - ./python/src:/app
  mysql-server:
    image: mysql:8.0.44-debian
    container_name: dev_mysql
    restart: always
    volumes:
      - ./servers/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myrootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
    ports:
      - "42333:3306"
  pip:
    build: ./pip/.    
    volumes:
      - ./python/src:/app     