services:
  flask:
    build:
      context: ./dockerfiles
      dockerfile: flask.dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src/backend:/app
  pip:
    build:
      context: ./dockerfiles
      dockerfile: pip.dockerfile
    volumes:
      - ./src/backend:/app  

