services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --debug
  db:
    image: mysql:8.4
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myrootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
  npm:
    image: node:20
    working_dir: /app
    entrypoint: ["npm"]
    volumes:
      - ./frontend:/app


